[[registry]]
prefix = "docker.io"
location = "docker.io"

[[registry.mirror]]
location = "docker.m.daocloud.io"

[[registry.mirror]]
location = "mirror.ccs.tencentyun.com"

[[registry.mirror]]
location = "dockerproxy.com"

[[registry.mirror]]
location = "hub-mirror.c.163.com"

